name: 'check sync nb'
description: 'Make sure notebooks are in sync and cleaned'
inputs:
  DUMMY:
    description: 'dummy input so this workflow will work.  No input is required.'
    required: false
runs:
  using: "composite"
  steps: 
    - name: Attempt to read notebooks
      run: |
        nbdev_read_nbs
      shell: bash

    - name: Check if notebooks are clean
      id: clean
      run: |
        nbdev_clean_nbs
        if [ -n "$(git status -uno -s)" ]; then
          echo "::error::Detected notebooks that are not cleaned."
          echo "\n\nList of notebooks that are not clean:"
          git status -s
          exit 1;
        fi
      shell: bash
    - name: Check that library syncs with notebooks
      id: lib
      run: |
        nbdev_diff_nbs > _nbdev_diff_logs.txt
        if [ -n "$(cat _nbdev_diff_logs.txt)" ]; then 
          echo "::error::Detected notebooks that are not in sync with the library."
          cat _nbdev_diff_logs.txt
          if [[ $auto_fix == 'true' ]]; then 
            nbdev_build_lib
          fi
          exit 1;
        fi
      shell: bash
