name: 'docs'
description: 'rsync docs to static host'
inputs:
  ssh_key:
    description: 'private key'
    required: true
  hostname:
    description: 'hostname to rsync to'
    required: true
  username:
    description: 'username to use for rsync'
    required: true
  src_path:
    description: 'local path to rsync files from'
    required: false
    default: 'docs/_site/'
  dest_path:
    description: 'path on host to rsync files to'
    required: false
    default: ''
  delete:
    description: "Toggle the --delete flag on or off.  Set to any value to enable.  Disabled by default."
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - name: install rsync
      run: |
        [[ "$OSTYPE" == "darwin"* ]] && brew install rsync
        [[ "$OSTYPE" == "linux"* ]] && apt-get update && apt-get install -y rsync
      shell: bash
    - name: rsync
      run: |
        cd
        export HOME=`pwd`
        cd -
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        rsync $(echo ${delete:+'--delete'}) -e "ssh -o StrictHostKeyChecking=no" -az ${{ inputs.src_path }} ${{ inputs.username}}@${{ inputs.hostname }}:${{ inputs.dest_path }}
      shell: bash
