name: 'build-docs'
description: 'Create docs with nbdev'
inputs:
  username:
    description: 'rsync user'
    required: true
  hostname:
    description: 'rsync host'
    required: true
  dest_path:
    description: 'path to rsync to'
    required: true
  ssh_key:
    description: "SSH key for rsync" 
    required: true
  delete:
    description: "Toggle the --delete flag on or off for rsync.  Set to any value to enable.  Disabled by default."
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - name: Create docs
      shell: bash
      env:
        JEKYLL_ENV: 'production'
        SSH_KEY: ${{ inputs.ssh_key }}
        delete: "${{ inputs.delete }}"
      run: |
        cp -r docs_src docs
        pip install -Uq nbdev fastcore
        pip install -Uq -e .[dev]
        pip install -U 'jupyter_client<7'
        nbdev_build_docs
        cd docs 
        bundle i
        bundle exec jekyll build --strict_front_matter
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        rsync $(echo ${delete:+'--delete'}) -az _site/ ${{ inputs.username }}@${{ inputs.hostname }}:${{ inputs.dest_path }}/
