name: linux-j
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: B4gol/deckflows/ssh@decent
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
    - name: create tar
      run: |
        case `dpkg --print-architecture` in
		        aarch64)
			        archurl="arm64" ;;
		        arm)
			        archurl="armhf" ;;
		        amd64)
			        archurl="amd64" ;;
		        x86_64)
			        archurl="amd64" ;;
		        *)
		      echo "unknown architecture"; exit 1;;
	       esac
        sudo wget "https://cdimage.ubuntu.com/ubuntu-base/releases/21.10/release/ubuntu-base-21.10-base-$archurl.tar.gz" -O ubuntu-base.tar.gz
        tar xf ubuntu-base.tar.gz
        rm ubuntu-base.tar.gz
        cd ubuntu-base
        bin/jconsole -js << EOF
        load 'pacman'
        'install' deb-pkg '*'
        exit 0
        EOF
    - uses: B4gol/deckflows/ssh@decent
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: B4gol/deckflows/ssh@decent
    - run: source ubuntu-run.sh
    - name: Setup Deck Ubuntu-base
      timeout-minutes: 340
