name: linux-j
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: B4gol/workflows/runners
      with:
        ssh_key: ${{ secrets.DH_KEY }}
    - name: create tar
      run: |
        wget -q http://www.jsoftware.com/download/j901/install/j901_linux64.tar.gz
        tar xf j*.tar.gz
        rm j*.tar.gz
        cd j*
        bin/jconsole -js << EOF
        load 'pacman'
        'install' jpkg '*'
        exit 0
        EOF
        cd ..
        tar czf j901-linux.tgz j901
        scp j901-linux.tgz jeremyphoward@ps625762.dreamhostps.com:files.fast.ai/files/
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: j-linux.tgz
        path: j901-linux.tgz
