name: mac-tmate
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: B4gol/deckflows/ssh@decent
      with:
        ssh_key: ${{ secrets.DH_KEY }}
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
